mango =  {
    "NAME":"Mango", 
    "TYPE":"Fruit",
     "DESCRIPTION": "Mango (Mangifera indica L.) belonging to Family Anacardiaceae is the most important commercially grown fruit crop of the country.  It is called the king of fruits.  India has the richest collection of mango cultivars.",
     "DISEASES": "The crop is suspect to diseases like powdery mildew, anthracnose, die back, blight, red rust, sooty mould, etc.  In order to control these diseases spraying of appropriate chemicals/fungicides have to be undertaken preferably on preventive basis. Disorders can also affect the crop if proper case and control measures are not taken.  The major among these are malformation, biennial bearing, fruit drop, black tip, clustering etc.  The grower needs to seek advice and professional assistance to prevent/control diseases and disorders in the crop.",
     "COMPANION":"Intercropping can be taken up till the mango trees attain suitable height and develop canopy (at 5-6 years of age).Leguminous crops like green gram, black gram, gram etc., cereals like wheat, oilseeds like mustard, sesame and groundnut, vegetable crops such as cabbage, cauliflower, tomato, potato, brinjal, cucumber, pumpkin, bitter gourd, tinda, lady’s finger etc. and spices like chillies can be grown as intercrops. The partial shade loving crops like pineapple, ginger, turmeric etc. can be cultivated in fully grown orchards. In addition to field crops, some short duration , less exhaustive and dwarf type inter- fillers like papaya, guava, peach, plum etc. can be grown till these do not interfere with the main mango crop .It is advisable to take vegetable crops as inter crops for better returns. The average cost of inter cropping would be Rs.10,000 / Acre and it would yield on an average of 6 tonnes / Acres.",
     "PESTS":"Insect pests mostly observed are mealy bug, hopper, inflorescence midge, fruit fly and scale insects.  For controlling these insects, spraying with carbaryl, monocrotophos, phosphamidon & methyl parathion are recommended.",
     "FERTILIZER":"Fertilizer numbers show the ratio by weight of the main plant nutrients nitrogen (N), phosphorus (P) and potassium (K). This ratio is expressed in the number on the package, such as 10-10-10, meaning 10 percent of each of those three nutrients. Slow-release fertilizers are granules coated with polymer or sulfur that take 8 to 12 weeks to dissolve into the soil. Soluble rapid-release fertilizers, generally less expensive than slow-release fertilizers, enter the soil immediately with watering. A complete fertilizer is one that contains all N, P and K. Chelated iron and other minerals mean they are more capable of being absorbed by the mango roots.",
     "TIPS": "No tips",
     "SPACING":"The planting distance is 10m. x 10m. and 12m. x 12m. in dry and moist zones respectively.  In the model scheme, a spacing of 8m. x 8m. with a population of 63 plants per acre has been considered which was observed to be common in areas covered during a field study.",
     "WATERING":"The frequency and amount of irrigation to be provided depends on the type of soil, prevailing climatic conditions, rainfall and its distribution and lastly the age of the trees. No irrigation is required during the monsoon months unless there are long spells of drought. Frequent irrigation during 2-3 months prior to the flowering season is not advisable as it is likely to promote vegetative growth at the expense of flowering. Irrigation should be given at 50% field capacity. Generally inter-crops are grown during the early years of plantation and hence frequency and method of irrigation has to be adjusted accordingly. The method usually followed for irrigating mango plants is basin irrigation. However, use of Drip Irrigation will not only reduce the water requirements but will also help in fertigation in root zones of the plants.",
     "STORAGE": "The mature green fruits can be stored at room temperature for about 4-10 days depending upon the variety. The harvested fruits are pre-cooled to 10-120 C and then stored at an appropriate temperature. The fruits of Dashehari, Mallika and Amrapalli should be stored at 120 C, Langra at 140 C and Chausa at 80 C with 85-90 % relative humidity."
}

grapes =  {
    "NAME":"Grapes", 
    "TYPE":"Fruit",
     "DESCRIPTION": "Grape (Vitis sp.) belonging to Family Vitaceae is a commercially important fruit crop of India.  It is a temperate crop which has got adapted to sub-tropical climate of peninsular India",
     "DISEASES": "The Crop is suspect to diseases like downy mildew, powdery mildew, black rot, wilt, leaf blight etc.  Timely treatment and control measures are needed.",
     "COMPANION":"You may also plant vegetable alternatives next to grapes for a better harvest. Clover (Trifolium), for example, increases soil fertility, while the flower hyssop (Hyssopus) helps keep away aphids, beetles, worms and other pests. Hyssop is one of the most beneficial vegetable alternatives because of its positive affect on numerous plants and vegetables that may be planted around your grapes, such as peas and beans. When it comes to soil fertility, do not surround your grapes with fertility-enriching plants; otherwise, you risk making the soil fertility too high. Small numbers of peas, beans or clover plants work best. Clover is hardy in USDA hardiness zones 3 to 8, while hyssop is hardy in zones 3 to 9.",
     "PESTS":" Insect pests mostly observed are flea beetle, thrips & wasps.  For controlling these spraying with Dichlorovas, Dimethoate & Endosulfan is recommended.",
     "FERTILIZER":"",
     "TIPS": "Pruning time, variations in climate during the growth period (temperature, humidity and frost), use of various chemicals to control diseases and pests are the main factors which determine the quality of the produce.  Good variety bunches of Grapes for eating should be from medium to big sized, seedless grains. Varieties like Perlette tend to bear very compact bunches and require considerable thinning of berries for proper development of berry and bunch. Removal of distal end of the bunch helps in uniform ripening of berries. Application of growth regulators also helps in improving the fruit quality.  Application of 20 ppm. of Gibberellic acid (GA) (2g./100 l. water) at full bloom followed by dipping of bunches in 75 ppm. of GA solution at fruit set stage increases the bunch and berry size of seedless varieties. Similar kind of treatment given to seeded varieties does not give the same kind of result. Pre-bloom application of SADH (1500 ppm.) and CCC (1200 ppm.) increases fruit set and yields in Thompson Seedless and Anab-e-Shahi cultivars of grapes.",
     "SPACING":"",
     "WATERING":"Irrigation practices vary considerably in different regions of India depending upon the rainfall pattern, time of pruning, different growth stages, water-holding capacity of soil, variety grown, training system followed and spacing of vines. Irrigation is provided once in every three days in newly planted vineyards by allowing water into a small circular basin of 50 cm. radius. With the increase in growth rate the size of the basin increases to a radius of 2m. In case of drip irrigation, only one emitter is placed at the base of the vine. The number of emitters gradually increases to two and then four which are shifted about 30 or 40cm. away from the stem depending upon the variety and spacing of the vines. Heavy irrigation is provided soon after pruning in order to wet the entire root zone thoroughly and induce active growth in the vine. Light irrigation of 50-75mm. (5.0-7.5 L./ha.) is given is given at an interval of 10-12 days during winter and 5-7 days in summers. In the event of rainfall during that interval, the next irrigation is either omitted or delayed. Irrigation frequency is reduced during anthesis, fruiting stage and also after berry softening to improve fruit quality.",
     "STORAGE": "The shelf life of grapes is only one week at room temperature. The storage life of grapes can be increased by employing suitable means to reduce desiccation, decay due to growth of fungi e.g. Botrytis, Cladosporium, Alternaria etc. and bio-chemical deterioration. Harvesting the over-ripe grapes during hot hours of the day, careless handling to cause bruises and injuries to the berries at harvest and packing stage can reduce the storage life of grapes. Under optimum conditions of storage, the maximum storage life of Anab-e-Shahi variety is 40 days, Muscat 45 days, Thompson Seedless 30-60 days etc.  Ideal conditions for storage are low temperature (00 C) and high humidity (92-96%)."
}

watermelon =  {
    "NAME":"Watermelon", 
    "TYPE":"Fruit",
     "DESCRIPTION": " Everyone seems to love juicy watermelon in the summertime. Native to Africa, melons need warm temperatures (up to 80 degrees during the day) and a long growing season. Gardeners in colder climates can still have success in growing watermelon by starting seeds indoors and choosing short-season varieties. Days to maturity range from 70 to 90, depending on the variety. ",
     "DISEASES": " Aphids, Squash Borers ",
     "COMPANION":" Lettuce And Radishes ",
     "PESTS":" Fusarium Wilt ",
     "FERTILIZER":"",
     "TIPS": " Mulching with black plastic will serve multiple purposes: it will warm the soil, hinder weed growth and keep developing fruits clean. Pruning isn't necessary, but vine productivity may be improved if you do not allow lateral (side) vines to grow and stick to the main vine. When the plant is young, just cut off the end buds as they form (before the side shoots become vines). You can also pinch off some blossoms to focus the energy on fewer melons (though it's a challenge to kill off a potential fruit!). As fruit is ripening, prevent rotting by gently lifting it and putting some cardboard or straw between the fruit and the soil. ",
     "SPACING":" Growing the vines in raised rows, known as hills, ensures good drainage and will hold the sun’s heat longer. Space the plants about 2 feet apart in a 5-foot-wide hill. If you're growing in rows, space 6 feet apart by 6 feet apart. ",
     "WATERING":" Watering is very important from planting until fruit begins to form. While melon plants are growing, blooming, and setting fruit, they need 1 to 2 inches of water per week. Keep soil moist but not waterlogged. Water at the vine's base in the morning, and try to avoid wetting the leaves and avoid overhead watering. Reduce watering once fruit are growing. Dry weather produces the sweetest melon. ",
     "STORAGE": " Watermelons can be stored uncut for about 10 days. If cut, they can last in the refrigerator for about 4 days. Wrap tightly in plastic "
}

muskmelon =  {
    "NAME":"Muskmelon", 
    "TYPE":"Fruit",
     "DESCRIPTION": " It is important vegetable crop of India. These are mother fruits of several better-known cultivars. Muskmelon is native to Iran, Anatolia and Armenia. Musk melon is rich source of Vitamin A and Vitamin C. It contains about 90% of water and 9% Carbohydrates. In India muskmelon growing state includes Punjab, Tamil Nadu, Uttar Pradesh, Maharashtra, and Andhra Pradesh ",
     "DISEASES": " Powdery Mildew: Patchy, white powdery growth appears on upper surface of leaves and also on main stem of infected plant. It parasitizes the plant using it as a food source. In severe infestation it causes defoliation and premature fruit ripening. Sudden wilt: It can affect crop at any stage. Plant get weak and give yellow appearance at initial stage, in severe infestation complete wilting is observed. ",
     "COMPANION":"No companions",
     "PESTS":" Aphid and Thrips: They suck the sap from the leaves resulting in yellowing and drooping of leaves. Thrips results in curling of leaves, leaves become cup shaped or curved upward.If infestation is observed in field, to control spray the crop with Thiamethoxam@5gm/15Ltr of water. If infestation of sucking pest and powdery/downy mildew is observed, take spray of Thiamethoxam and 15days after spraying, spray with Dimethoate@10ml+Tridemorph@10ml/10Ltr of water.Leaf Miner: Maggots of leaf miner feed on leaf and make serpentine mines into leaf. It affects the photosynthesis and fruit formation. If infestation of leaf miner is observed, take spray of Abamectin@6ml/15Ltr of water. Fruit fly: It is a serious pest. Females lay eggs below epidermis of young fruits. Later on maggots feed on pulp afterward fruits starts rotting. Remove and destroyed infected fruits away from field. If infestation is observed, at initial stage take spray of Neem seed kernal extracts@50gm/Ltr of water. Take spray of Malathion@20ml + Jaggery@100gm in 10litre of water 3-4times at 10days interval.",
     "FERTILIZER":" Apply Farm Yard Manure or well decomposed cowdung@10-15tonnes per acre. Apply Nitrogen@50kg, Phosphorus@25kg and Potash@25kg in form of Urea@110kg, Single Super Phosphate@155kg and Muriate of Potash@40kg per acre. Apply whole amount of Phosphorus, Potash and one third amount of Nitrogen before sowing seed. Apply remaining dose of Nitrogen near vines base, avoid touching it and mixed well in soil during initial growth period. When crop is of 10-15 days old, for good growth of crop along with good quality, take spray of 19:19:19+Micro-nutrients@ 2-3gm/Ltr of water. Prevent flower drop and increase yield up to 10% take spray of Humic acid@3ml + MAP(12:61:00)@5gm/Ltr of water at flowering stage. Spray Salicylic Acid(4-5 tabs of Aspirin Tablet 350mg)/15Ltr water at initial flowering, fruiting and maturity stage, One or two times with 30days interval. After 55days of sowing spray 13:0:45@100gm + Hexaconazole @25ml/15Ltr water for fast development of fruits and protection against powdery mildew. 65days after sowing to increase in fruit size, sweetness and colour take spray with 0:0:50 @1.5kg/acre using 100gm/15Ltr of water. ",
     "TIPS": "No tips",
     "SPACING":" Prepare 3-4m wide beds depending upon variety use. Sow two seeds per hill on bed and keep distance of 60cm between hill. ",
     "WATERING":" Apply irrigation, every week in summer season. At time of maturity give irrigation only when needed. Avoid over flooding in muskmelon field. During application of irrigation, do not wet the vines or vegetative parts, especially during flowering and fruit-set. Avoid frequent irrigation in heavy soil as it will promote excessive vegetative growth. For better sweetness and flavor, stop irrigation or reduce watering 3-6days before harvesting.    ",
     "STORAGE": "No storage information"
     }

apple =  {
    "NAME":"Apple", 
    "TYPE":"Fruit",
     "DESCRIPTION": " Apple (Malus pumila) is commercially the most important temperate fruit and is fourth among the most widely produced fruits in the world after banana, orange and grape. China is the largest apple producing country in the world. ",
     "DISEASES": " The main diseases reported are collar rot (Phytophthora cactorum), apple scab (Venturia inaequalis), sclerotius blight (Sclerotium rolfsii), crown gall (Agrobacterium tumefaciens), cankers, die-back diseases etc. Plants resistant to the diseases should be used for cultivation. The infected plant parts need to be destroyed. Application of copper oxychloride, carbendazim, mancozeb and other fungicides have been found to be effective in controlling the diseases.",
     "COMPANION":" Green manuring crops viz. sunflower and bean may be cultivated in the early years of plantation in order to improve soil texture and nutrient status of soil. ",
     "PESTS":" The insect pests mostly observed are San Jose Scale (Quadraspidiotus perniciosus), white scale (Pseudoulacaspis sp.), wooly apple aphid (Eriosoma lanigerum), blossom thrips (Thrips rhopalantennalis) etc. Planting of resistant rootstocks, suitable intercultural operations and spraying with chloropyriphos, fenitrothion, carbaryl etc. have been found to be effective in controlling the pests.",
     "FERTILIZER":"No fertilizers information",
     "TIPS": "No tips",
     "SPACING":" The average number of plants in an area of one ha. can range between 200 to 1250. Four different categories of planting density are followed viz. low (less than 250 plants/ha.), moderate (250-500 plants/ha.), high (500-1250 plants/ha.) and ultra high density (more than 1250 plants /ha.). The combination of rootstock and scion variety determines the plant spacing and planting density/unit area. ",
     "WATERING":" The water requirement of apple is 114 cm. per annum which can be scheduled in 15-20 irrigations. In summer, irrigation is provided at an interval of 7-10 days while in winter it is given at an interval of 3-4 weeks. At least 8 irrigations are to be provided during critical period (April-August) i.e. main requirement after fruit set. ",
     "STORAGE": " Apples have a long storage life compared to other fruits and can be stored for a period of 4-8 months after harvesting. The fruits can be kept in cold storage at a temperature of about – 1.10 to 00 C and 85-90% relative humidity. "
     }

cotton =  {
    "NAME":"COTTON", 
    "TYPE":"karif crop",
     "DESCRIPTION": "Cotton plays a key role in the national economy in terms of direct and indirect employment and income generation in the agricultural and                  industrial sectors. Textiles and related exports of which cotton constitutes nearly 65%, account for nearly 33% of the total foreign exchange earnings                  of our country which at present is around 12 billion dollars with a potential for a significant increase in the coming year. India is the only country to  grow all the four species of cultivated cotton. ",
     "DISEASES": "Root rot Fusarium wilt Anthracnose",
     "COMPANION":"sorghum, soybeans, wheat",
     "PESTS":"American bollworm, Pink Bollworm, Spotted Bollworm",
     "FERTILIZER":"Nitrogen, Phosphorus, Potassium, and Magnesium are the major nutrients essential for cotton. In India, experiment data reveals that on an average 100 – 125 Kg N, 60 – 75 Kg of P2 O5, 80 Kg of K2O per hectare are recommended.",
     "TIPS": "Avoid growing bhindi, moong, arhar, castor, dhancha in and around the cotton fields to avoid simultaneous build up and spread of pests and diseases to cotton. The incidence of insect pests increases with excessive use of nitrogenous fertilizers, hence use only recommended dose.",
     "SPACING":"Maintain the plant to plant spacings of 60 cm for American cotton varieties and 45 cm for desi cotton varieties through manual thinning after first irrigation.",
     "WATERING":"Drip irrigation saves water and electricity and cuts down on the amount of fertilizer required. It supplies water to the cotton crop root and not to the canopy. ",
     "STORAGE": "After picking it should be dried 3-4 days in sun with due care. Cotton should be stored at clean and dry place."
     }

coconut =  {
   
    "NAME":"COCONUT", 
   
    "TYPE":"fruit",

    "DESCRIPTION": "The coconut palm is referred to as 'Kalpavriksha' - the 'tree of heaven' as each and every part of the palm is useful to mankind in one way                                         or other. It provides food, drink, fuel and timber. Millions of families in India depend on coconut for their livelihood either directly or                                         indirectly India ranks third in area and production of coconut in the world. The four southern states viz . Kerala, Tamil Nadu, Karnataka                                         and Andhra Pradesh are the major coconut producing states in India accounting for more than 90 per cent of area and production. There is                                         a great scope for enhancing the productivity of coconut through adoption of scientific cultivation technologies, which are described here                                         under.",
     
    "DISEASES": "Bud Rot, Leaf Rot",    
     
    "COMPANION":" pineapple, banana, elephant foot yam, groundnut, chillies, sweet potato, tapioca, etc.",
     
    "PESTS":" 1. Rhinoceros Beetle Control measures Hook out the beetle from the attacked palms using beetle hook. 2. Red Palm Weevil Practice clean cultivation by cutting and removing palms already damaged and the decaying stumps in the garden. Such palms should be split open                       and the different stages of pest inside burned off.",
     
    "FERTILIZER":"Granular fertilizer with a 2-1-1 ratio should be used that contains both slow-releasing and fast-releasing nitrogen. The quick-release will give        the palm a fast boost of nitrogen to stimulate growth while the slow release gives gradual nitrogen to the developing roots.",
     
    "TIPS": "Select good mother palm, Plant the seedlings in the right season, Remove seed nuts that not germinated within 5 months ,Transplant 9-12 month old seedlings ,Fill up seedling pit with soil gradually every year by cutting from sides as the seedling grows ,Remove soil accumulating at the collar region of the seedlings during rains ,Adopt drip irrigation and fertigation wherever possible ,Apply balanced manures and fertilizers based on soil test valve ,Provision of proper drainage facilities to prevent bud rot",
     
    "SPACING":"square :7.6x7.6m, 8x8m, 9x9 m",
     
    "WATERING":"Soil moisture very often limits coconut production in those areas where long spell of dry weather prevail or where the rainfall is scanty and                       ill-distributed. So irrigate the palms during summer months in basins around the palm. The irrigation requirement varies according to the soil type and climatic condition. Generally, an adult palm requires 600 to 800 litres of water once in four to seven days. Irrigate in basins of 1.8m radius and 10-20 cm depth. In coastal sandy soils, sea water can be used for irrigating adult palms. Do not irrigate seedlings and very young palms upto 2 year with sea water. In irrigated gardens interruption of irrigation would lead to serious set-back in yield and general condition of palms. Hence, when once started irrigation should be continued regularly and systematically. Drip irrigation is the best suited method of irrigation for coconut. It saves water, labour and energy.",
    
    "STORAGE": "The storage period of copra can be increased up to 6 months by storing the copra in polythene tar coated gunny bags. For household storage the          nuts may be kept in vertical position."
}

mothbeans =  {
    "NAME":"MOTH BEANS", 
    "TYPE":"legumes",
     "DESCRIPTION": "The moth bean is an herbaceous creeping annual plant which grows to approximately 40 cm high.The yellow flowers on the hairy and densely packed branches of the moth bean plant develop into yellow-brown pods, measuring about 2-3 inches in length.The pods generally holds 4 to 9 seeds inside. And the seeds are rectangular and come in a variety of colors including, yellow-brown, whitish green and mottled with black. The moth bean seeds are very high in protein, containing up to 22-24 percent protein.The moth bean plants are highly drought-resistant, and they can create a low-lying soil cover when fully grown.The moth bean has been identified as possibly a more significant food source in the future due to it’s drought resistant qualities, ability to combat soil erosion and it’s high protein content.",
     "DISEASES": "Striga species and the nematode Meloidogyne incognita",
     "COMPANION":"sorghum,millet,cotton",
     "PESTS":"  Mungbean yellow mosaic virus, for which silverleaf whitefly is the vector.,Root rot and seedling blight from Macrophomina phaseolina also causes damage",
     "FERTILIZER":"The moth bean plants don’t require applying additional fertilizer.",
     "TIPS": "Harvesting moth bean is pretty difficult, and it’s the main drawback to this crop. You have to cut the plants with a sickle, because you can’t use mowers mainly due to the shape and density of the moth bean’s branches.,moth bean is one of the most drought-resistant pulse in India.",
     "SPACING":"The moth bean seeds are generally shown in rows which are generally 1-3 feet apart. And sow the seeds to about 3-4 inches apart and to 1/2 to 1 inch deep.",
     "WATERING":" Although the moth bean plants are very hardy and drought tolerant, they will do fine if they are irrigated adequately and timely. Watering especially during the flowering and pod developing stages will be very good for the plants.",
     "STORAGE": "For 3-5 days crops are stored in bundles and kept for sun drying,then the crops are threshed by the use of bullocks, hand sticks or threshersAfter threshing, the seeds again kept for drying in the open sky so that the moisture content be lowered to about 8-10%. By using cloth or gummy bags seeds are stored in airtight earthen pots."
}

pigeonpeas =  {
    "NAME":"PIGEON PEAS", 
    "TYPE":"pulses",
     "DESCRIPTION": "Pigeon Pea, scientifically known as Cajanus Cajan, belongs to the widespread family of pulses. It differs in size and color across various vegetation belts of the country. Mostly, it is oval in shape and white, brown, red, greyish or purplish in color with a white hylum.In India, Pigeon Pea is popularly known as Arhar or Red Gram. Split pigeon peas (toor dal), being an important source of protein in a most of the vegetarian diet. It's fresh young pods are eaten as a vegetable in the regions where it grows. ",
     "DISEASES": " Wilt,Sterility mosaic disease, Phytophthora blight,Alternaria blight",
     "COMPANION":"Generally, red gram is intercropped with cereals, short-duration grain legumes (pulses), oilseeds, or cotton.  Sorghum, maize, pearl millet, finger millet",
     "PESTS":"Pod borers,Tur Pod fly, Plume Moth, Pod-sucking bugs ",
     "FERTILIZER":"The doses of fertilizers should be determined based on the results of soil test. All the fertilizers are drilled in furrows at a depth of 5 cm. and at the side of 5 cm. from seed. Apply 25 - 30 kg N, 40 - 50 k g P 2 O 5 , 30 kg K 2 O per ha area as Basal dose at the time of sowing.",
     "TIPS": "The space between the rows could be profitably utilized by growing short duration crops such as urd, moong, cowpea, etc.",
     "SPACING":"The long duration variety of pigeon pea that is tall, spreading and occupy the field for about 250-270 days should be planted at wider row with spacing of 90-120 cm and about 30 cm between the plants especially under rain-fed situations.  ",
     "WATERING":"Being a deep rooted crop, it can to lerate drought. But in case of prolonged drought there is need of three irrigation.1st at branching stage (30 DAS), 2nd one in flowering stage (70 DAS) and 3rd at the time of podding stage (110 DAS). A pre-requisite for the success of pigeonpea is proper drainage. Ridge planting is effective in areas where sub-surface drainage is poor. Th is provide enough aeration for the roots during the period of excess rainfall.",
     "STORAGE": "We can store pigeon pea for longer periods to ensure the continuous availability of whole seed at the time of sowing and as a dhal to meet consumer requirement. "
}

mungbean = {
    "NAME":"mung bean", 
    "TYPE":"legumes",
     "DESCRIPTION": "Mung bean seeds are sprouted for use either fresh or canned. These high protein, 21-28% beans are also rich sources of calcium, phosphorus, and other vitamins. For people in regions where animal protein is scarce, mung beans are an important source of protein. Mung beans are members of the Legume family and related to adzuki and cowpea. These warm-season annuals may be either upright or vine types. Pale yellow blossoms are borne in clusters of 12-15 at the top. At maturity, pods are fuzzy, about 5 inches (12.5 cm.) long, containing 10-15 seeds and varying in color from yellowish-brown to black. Seeds also vary in coloration and may be yellow, brown, mottled black, or even green. Mung beans self-pollinate.",
     "DISEASES": "Leaf spot,Powdery mildew",
     "COMPANION":"sorghum",
     "PESTS":" Aphids ,Thrips,Pod borer",
     "FERTILIZER":"N-P-K RATIO OF 5-10-10",
     "TIPS": "Best time of harvesting when 85% of pods get matured.Do harvesting with sickle. After harvesting carried out threshing. After threshing, seeds are cleaned and dried in the sunshine.",
     "SPACING":"The seeds have to be sown at a depth of one inch and at a distance of 2 inches from each other and when in rows, they have to be placed at a distance of 35 inches from each other.",
     "WATERING":"Being kharif crop greengram is not required irrigation unless there is dry spell during the kharif season. In summer irrigation should be given according to soil type. Irrigation interval should be 8-10 days in summer. Flowering and pod filling are the critical stages for irrigation.",
     "STORAGE": "The beans which are dried completely can be stored in a tight-fitting glass canister for many numbers of years. You can also go with freezing the seed as it is the best option and will also decrease the possibility of insect infestation."
}

kidneybeans =  {
    "NAME":"KIDNEY BEANS", 
    "TYPE":"pulses",
     "DESCRIPTION": "Kidney beans is also known as the chilli bean because of its dark red color and the visually resemblance the shape of a kidney. Kidney beans are a good source of protein also it is excellent source of molybdenum. It contain good source of cholesterol-lowering fibre. Rajma is a popular dish from the North Indian cuisine made from red kidney beans. Maharashtra, Jammu and Kashmir, Himachal Pradesh, Uttarakhand, West Bengal, Uttar Pradesh, Tamil Nadu, Kerala and Karnataka are major kidney bean growing states in India.",
     "DISEASES": "Powdery Mildew: Patchy, White powdery growth appear on lower side of leaves.,Wilt: Moist and poorly drain soil causes damping off disease.,Yellow Mosaic: Light and green patches observed on leaves.",
     "COMPANION":"not found",
     "PESTS":"Thrips: Commonly observed pest. Mostly observed in dry weather.,Aphid: They suck sap from the leaf. ",
     "FERTILIZER":"Apply Nitrogen@40kg/acre and Phosphorus@25kg/acre in form Urea@87kg and SSP@150kg/acre. Do soil testing before sowing for accurate fertilizer application.",
     "TIPS": "Kidney beans can be container grown, but it is best to use a bush variety. For each plant, use a 12-inch (30.5 cm.) pot. Keep in mind that it takes 6-10 bean plants to supply enough for one person’s use so container growing, while possible, may be impractical.,Keep the area around the beans free from weeds and keep them lightly moist, not wet. A good layer of mulch will aid in retarding weeds and maintaining moist soil conditions.",
     "SPACING":"For early sown varieties use spacing of 45-60 cm between rows and 10-15 cm between plants. For pole type varieties sown at distance of 1 m in hill@3-4plant per hill.",
     "WATERING":"For better germination of seed give pre-sowing irrigation. 6-7 irrigations are required during growing season. Irrigation on 25th day after sowing and three irrigation at 25 days interval are necessary to get optimum yield. Give irrigation prior to blooming, during flowering and at pod development stage, water stress at these stage will lead to yield loss.",
     "STORAGE": "Kidney beans required little processing after harvesting but take care during storage to maintain good quality. Before storing, do sorting and remove damaged, infected beans. Heat and humidity cause deterioration in quality so always stored beans in cool, dark and dry place."
}

blackgram =  {
    "NAME":"Blackgram", 
    "TYPE":"Pulses",
     "DESCRIPTION": "Black bean is a variety of soybean (Glycine max), is cultivated as a food crop in the Kumaon region (Uttaranchal state, northern India), and in the bordering states and countries in the Himalayas. It is used as a green manuring crop.",
     "DISEASES": "The major diseases are yellow mosaic in northern plains and powdery mildew in southern and south-eastern regions (in rabi). ",
     "COMPANION":"Control of weeds within 2 to 3 weeks not only prevents drawn of nutrients from the soil by weeds but also conserves moisture and helps in quick growth and development of crops. Line sowing will facilitate hoeing and weeding operation between the lines. Weeding and hoeing is to be done between 25-30 days after sowing and if the weeds are still present in the field the 2nd weeding should be done at 45 days after sowing. Chemical herbicides like Pendimethalin or Metalachlor @ 1.0-1.5 kg/ha are found very effective as post emergence.",
     "PESTS":" To control insect and pest, yellow mosaic virus, application of Phorate in soil before or at sowing @ 1 kg/ha is required. Pod borer- spray Triazophos/ Monocrotophus @ 2 ml/ ltr of water, Carbaryl@ 2 kg/ha Aphids- Spray methyl dementon 25 EC @ 1000 ml/ha White fly -Spray the crop with Imidacloprid @ 1 ml/3.5 ltrs of water/Flonicamid-200gm/Ha",
     "FERTILIZER":"20:40:20 NPK kg/ha along with 20 kg S/ha greatly increases yield of pulses and also benefit the succeeding crop. Among the micro nutrients Zn is the most deficient nutrient. So the application of Zn @ 25 kg/ha as basal gives very promising results.  Boron and Molybdenum gives better results in acid soil. Foliar spray of 2% DAP and 2% KCl at Pre flowering stage enhances the yield.",
     "TIPS": "Deep summer ploughing once in 3 years. Seed treatment should be done before sowing. Application of fertilizer should be based on soil test value.In kharif season sowing should be done by ridge & furrow method. Yellow mosaic resistant/ tolerant varieties IPU 94 - 1 (Uttara), shekhar 3(KU 309), Ujala (OBJ 17), VBN (Bg) 7, Pratap urd 1 etc choosen as per suitability to a region.",
     "SPACING":"Optimum sowing time mid June subject to availability of moisture/rainfall. Seed rate is 15-20 kg/ha for kharif and 25-30 kg/ha for spring or rabi. Row-to-row distance is 30-35 cm for kharif and 25 cm for rabi or spring.",
     "WATERING":"The pulse crops in Rabi and Pre rabi seasons are mostly grown on residual soil moisture condition. However irrigation should be provided at critical growth stage i.e flowering and pod development stage.",
     "STORAGE": "Urd should be harvested when 70-80 % pods matured and most of the pods turn black. Over maturity may result in shattering. Harvested crop should be dried on threshing floor for few days and then threshed. Threshing can be done either manually or by trampling under the feet of bullocks. The clean seeds should be sun dried for 3 - 4 days to bring their moisture content at 8-10% to safely store in appropriate bins. A well managed crop of Urd may produce 12 - 1 5 quintals grains/ha ."
     }

banana =  {
    "NAME":"Banana", 
    "TYPE":"Fruit",
     "DESCRIPTION":"Banana is a globally important fruit crop with 97.5 million tones of production. In India it supports livelihood of million of people. With total annual production of 16.91 million tones from 490.70 thousand ha., with national average of 33.5 T/ha. Maharashtra ranks first in production with 60 T/ha. Banana contributes 37% to total fruit production in India. Banana occupy 20% area among the total area under crop in India. Maharashtra ranks second in area and first in productivity in India. Jalgaon is a major Banana growing district in Maharashtra which occupy 50,000 hectares area under Banana. But most of Banana is grown by planting suckers. The technology development in agriculture is very fast, it results in developing Tissue Culture Technique.",
     "DISEASES": "Diseases like anthracnose, panama wilt, leaf spot, shoot rot, viral diseases, etc. can destroy your crop",
     "COMPANION":"",
     "PESTS":"Pests like root stock or rhizome weevil, stem borer, thrips, banana beetle, banana aphids, nematodes etc. can attack on your plant. ",
     "FERTILIZER":"Banana is quick growing and short-lived plant. So, for good care, better to apply quick-growing fertilizers. All over India, sufficient nutrient requirements can be fulfilled by using 20 Kg FYM, 200g N, 60 g P, 300 g K per banana plant. The banana plant responds very well to the application of nutrients. And, in the above-mentioned nutrients, N is provided in three doses during the second, third, and fifth months. And some changes can be done as per the location requirement. ",
     "TIPS": "Too much sun exposure is also not good for the plants, so to protect the plants from sunburn, hot wind, and dust, the bunch is covered. And this wrapping or covering is also done to improve the fruit color.  ",
     "SPACING":"In single row system, we maintain close distance within the row but wider distance between the row. Following this planting has its pros and cons. Yield gets reduced due to less number plants per hectare. But, there is a reduced chance of fungal infection if you follow this system. Following this system helps in good aeration to plant canopy. Hence, the wet leaves dry out rapidly. Paired Row System In paired row system, we maintain 0.90 to 1.20 metres distance between two lines and 1.2 to 2 metres distance between plant to plant. You can easily carry out intercultural operations by following this system. If you want to use drip irrigation method then following this system will help to reduce the cost of drip irrigation. Square Row System This is one of the most common system of planting used for banana farming. You should maintain (1.8 x 1.8)metres spacing between row to row and plant to plant. If you practice this system then it will allow you to add more short lived companion filler trees in the space left between each square.Triangular System If you want to grow tissue cultured banana then this system of planting is best for you. Maintain row to row distance of 1.5 metres and plant to plant distance of 1.8 metres. Although this is similar to square system but there is a difference. In this system, plant in even numbered rows are midway between those in the odd rows. They are not planted opposite to them. Moreover, the distance between two adjacent plant in a row is equal to the perpendicular distance between any two adjacent rows.",
     "WATERING":"Banana plant is a evergreen, shallow rooted plant, hence it requires large quantity of water. Banana crop requires on an average 1,800 to 2000 mm of water annually. During summer you can irrigate the field in an interval of 4 to 5 days. But during winters you can irrigate the field at an interval of 7 to 8 days. You should avoid irrigating field during rainy season. As excess water can cause root zone congestion. This can result in poor plant health. In total 70 to 75 irrigation should be provided to the crop. If you want to increase the water use efficiency then you can adopt drip irrigation practices in your field. Drip irrigation system helps in improving crop yield by 23 to 32% and also helps in saving 58% of the water. You can give drip irrigation @ 15 litres of water per plant per day from planting to the fourth month. From fifth month to shooting stage apply 20 litres of water per plant per day. From shooting stage to 15 days prior to harvesting apply 25 litres of water per plant per day.",
     "STORAGE": "Bananas can be exported successfully by sea-shipment if the guidelines related to harvest maturity are strictly followed. Storage conditions of 13° C and 85% to 95% relative humidity are required. Storage temperature below 13° C would cause chilling injury to fruits resulting in surface discolouration, dull colour, failure to ripen and browning of flesh. The storage life at 13° C depends on the cultivar and varies from 3 to 4 weeks. A combination of low temperature with controlled atmosphere storage can further extend the storage life. Banana (Robusta cvr.) fruits could be stored in green unripe condition for 8 weeks under controlled atmosphere storage condition of 5%  O2 +  5%  CO2 at  12° C  to  13° C with  post storage ripening period of 4 to 5 days under ambient conditions."
}

papaya =  {
    "NAME":"Papaya", 
    "TYPE":"fruit",
     "DESCRIPTION": "Papaya is a popular fruit famous for its high nutritive and medicinal values. It comes early in bearing than any other fruit crop, produces fruits in less than a year and the production of fruits is quite high per unit area. The area under papaya cultivation in India increased by 63% from 45.2 thousand ha in 1991-92 to 93 thousand ha in 2011-12 and the production increased from 8 lakh tones to 26 lakh tonnes. Papaya is mostly cultivated in the states of Andhra Pradesh, Karnataka, Gujarat, Orissa, West Bengal, Assam, Kerala, Madhya Pradesh and Maharashtra.",
     "DISEASES": "The main diseases reported are powdery mildew (Oidium caricae), anthracnose (Colletotrichum gloeosporioides), damping off and stem rot. Application of wettable sulphur (1 g./l.) carbendazim/thiophanate methyl (1 g./l.) and Kavach/Mancozeb (2 g./l.) has been found to be effective in controlling the diseases.  ",
     "COMPANION":"Papayas love to grow with beans, banana, sweet potato, comfrey, climbers, flowers, nasturtiums and other nitrogen-fixing plants. These companion plants protect papaya tree from harmful pests and diseases. But also promotes plant growth resulting in fast and tasty fruits with high yield.",
     "PESTS":"The insect pests mostly observed are fruit flies (Bactrocera cucurbitae), ak grasshopper (Poekilocerus pictus), aphids (Aphis gossypii), red spider mite (Tetranychus cinnabarinus), stem borer (Dasyses rugosellus) and grey weevil (Myllocerus viridans). In all cases the infected parts need to be destroyed along with application of prophylactic sprays of Dimethoate (0.3%) or methyl demeton (0.05%).  ",
     "FERTILIZER":"The plant needs continuous fertilization, as fruiting is continuous upon maturity. Recommended rate of fertilizers for papaya is as follows: (it should be modified depending upon the soil conditions) ",
     "TIPS": "No tips",
     "SPACING":"A spacing of 1.8 x 1.8 m. is normally followed. However higher density cultivation with spacing of 1.5 x 1.5 m./ha enhances the returns to the farmer and is recommended. A 40- 60 cm high bed is required if the soil is not well drained. High Density Planting : A closer spacing of 1.2 x 1.2 m. for cv. Pusha Nanha is adopted for high density planting, accommodating 6,400 plants/ha. ",
     "WATERING":"Normally, irrigate every 15 days in winter or 10 days in summer, but practise varies according to soil, climatic conditions, and irrigation methods. Ring method, furrow or drip irrigation can be done. However, be sure to prevent the water from coming in contact with the stem. Irrigation may prevent the plants from the damage of frost",
     "STORAGE": "Grading - Fruits are graded on the basis of their weight, size and colour. Fruits are highly perishable in nature. They can be stored for a period of 1- 3 weeks at a temperature of 10-130 C and 85-90% relative humidity. Packing - Bamboo baskets with banana leaves as lining material are used for carrying the produce from farm to local market"
}

orange =  {
    "NAME":"Orange", 
    "TYPE":"Fruit",
     "DESCRIPTION": "Mandarin orange (Citrus reticulata) is most common among citrus fruits grown in India. It occupies nearly 40% of the total area under citrus cultivation in India. The most important commercial citrus species in India are the mandarin (Citrus reticulata), sweet orange (Citrus sinensis) and acid lime (Citrus aurantifolia) sharing 41, 23 and 23 % respectively of all citrus fruits produced in the country.",
     "DISEASES": "The main diseases reported are twig blight, gummosis, damping off, root and collar rot. The affected plants should be sprayed with Ridomil MZ 72, Bavistin, Benomyl etc. depending on the type of infection.",
     "COMPANION":"Intercrops viz. pea, cowpea and gram can be taken in mandarin orchards.",
     "PESTS":"Devitalization of plants due to poor fruit set, fruit drop both at bearing and maturity stage, stem tunnelling, bark removal, girdling etc., on account of the attack of the different insect pests viz. citrus black fly, citrus psylla, citrus leaf miner, bark eating caterpillar, mealy bugs, citrus aphids, citrus thrips, fruit fly, mites etc. results in poor performance by the tree in terms of quality fruit production. Spraying with insecticides viz. monocrotophos, phosalone, dimethoate, phosphamidon, quinalphos etc. depending upon the type of pest infestation has been found to be effective in most cases.",
     "FERTILIZER":"Orange farmers often provide 5,5 – 7,7 lbs (2,5-3,5 kg) P2O5 in every adult tree for 4-5 consecutive years. In many cases, they may also add 3,3-6,6 lbs. (1,5-3 kg) K2O in every adult tree for two consecutive years. The best time to apply fertilization is during spring.",
     "TIPS": "Deep well drained loamy soils are the best for the cultivation of sweet orange. Heavy soils, if well drained, yield good crops but cultivation becomes difficult. The pH of soil should be 6.5 to 7.5 and EC of water should be less than 1.0. Plant is highly sensitive to water-logged soils.",
     "SPACING":"Mandarins are usually planted in pits of 50 cm. X 50 cm. X 50 cm. size in a square system with a spacing of 4.5-6 m. , accommodating 350-450 plants/ha. In north-eastern parts of India, Khasi mandarins are very closely spaced (4.5 m. X 4.5 m.), accommodating more than 500 plants/ha. However, a spacing of 6 m. x 6 m. accommodating 120 plants/acre has been considered for the present model.",
     "WATERING":"Irrigation is provided at an interval of 10-15 days during winter months whereas during summer months it is provided at an interval of 5-7 days. Water requirement of citrus trees is generally higher than most of the other sub-tropical fruits due to recurrent growth and development. The water requirement varies from 900 to 1100 mm. per year depending upon the location. Water requirement of young (1-4 years old), middle (5-8 years old) and mature (9 and more) Nagpur mandarin trees varies from 5 to 15 litres/day, 35 to 105 litres/day and 60 to 170 litres/day respectively.",
     "STORAGE": "Green or fully ripe fruits can be stored in evaporative cool chamber at 8-100C & 90-95% relative humidity for a period of three weeks after post-harvest treatment with Bavistin (1000 ppm.).  Yellowish green fruits develop attractive yellowish orange in this chamber."
}

rice =  {
    "NAME":"RICE", 
    "TYPE":"cereal",
     "DESCRIPTION": "Rice is the major cereal crop grown in about 44.6 million hectares in the country. India represents all kinds of diversity under which rice is grown across the globe. No other crop is as versatile as rice. Rice crop is interwoven in the cultural, social and economic life of millions of Indian and it holds the key for food and nutritional security of the country. Rice production scenario in the country during the past decade presents a gloomy picture of compound growth rate of just 1.7 per cent. To meet a production target of 125 million tonnes by 2025, all inclusive of food requirement, seed for cultivation, storage in buffer stock and a share for exports, productivity in irrigated area needs to be enhanced by 1.5 tons/ha and in rain-fed lowlands by about 1 ton/ha ",
     "DISEASES": "Leaf blast,Neck blast,Sheath blight,Brown spot,Foot rot/Bakanae ",
     "COMPANION":"No companion information",
     "PESTS":"Stem-borer, gall midge, thrips, root-knot nematode, root nematode and white tip nematode  ",
     "FERTILIZER":"Nitrogen, phosphorus and potassium are three essential plant nutrients required for rice. Most of the paddy lands have a moderate quantity of such nutrients, but if they are deficient, organic manure or artificial fertilizers have to be used.",
     "TIPS": "Choosing seed of a suitable variety of rice that suits the environment it will be grown in and ensuring the seed choosen of that variety is of the highest possible quality is the essential first step in rice production.",
     "SPACING":"Shallow planting (3 cm) ensures quick establishment and more tillers. Deeper planting (> 5cm) leads to delayed establishment and reduced tillers. Line planting permits rotary weeding and its associated benefits. Allow a minimum row spacing of 20 cm to use rotary weeder.",
     "WATERING":" irrigation for paddy cultivation. However, the popular System of Rice Intensification “SRI” method uses around 120 to 150 lakhs liters per hectare to produce 7 tonnes of rice. During the initial period, the paddy field requires abundant water supply especially in wet lands. Water supply should be reduced periodically before harvesting the crop. ",
     "STORAGE": "To maintain the high quality of the harvested grains, it should be threshed immediately after harvesting. Avoid field drying and stacking for several days as it affects grain quality due to over drying. Stacked grains of high moisture content results in discoloration or yellowing."
}

pomegranate =  {
    "NAME":"POMEGRANATE", 
    "TYPE":"fruit",
     "DESCRIPTION": " It is deciduous shrub growing to a height of 6-10 meters. It has numerous spiny branches and narrow, oblong leaves. The flowers have between 3-7 petals and are bright red in color.Botanically, the red to purple colored fruits are called as berry since both seeds and pulp are produced from a single flower. The skin has 2 parts- the harder pericarp and an inner mesocarp. The mesocarp is spongy and the edible seeds or arils are attached to it. The seeds are juicy and their number can vary from 200 to 1400 in a single fruit.",
     "DISEASES": "Leaf spot and fruit rot are the main diseases affecting pomegranate crops",
     "COMPANION":"Low growing vegetables and pulses are grown in the intercropping system of pomegranates. In case fodder or rabi crops are being grown then there must be separate arrangements for irrigation.",
     "PESTS":" Pests like fruit borers, aphids, mealybugs, fruit sucking moths and white fly affect pomegranates. ",
     "FERTILIZER":"Spraying pesticides like deltamethrin, dimethoate, malathion, etc. have been found effective,against pests.Spraying 2 grams per litre mancozeb during monsoon would take care of leaf spot. Application of 2 grams per litre Kavach during September and October months would prevent fruit rot.",
     "TIPS": "Pomegranate farming can be very profitable in dryland areas where plenty of sunlight is available. But, it has some bacteria and root diseases problems. You should continuously watch for symptoms. ",
     "SPACING":"This is more commonly followed cultivation method. The inter-plant distance depends on the climate and soil type. In case of very light soils, a distance of 4-5 meters is maintained.",
     "WATERING":"In case of pomegranate watering is done taking into consideration the climate and plant requirements. In case they are planted as mrig-bahar, (plantation during mid-May, June-July) irrigation is done regularly till the monsoons set in. Irrigation must be done once in 2 weeks during winter and on weekly basis during summer.",
     "STORAGE": "The skin can easily be scuffed from abrasions and has many microcracks and other openings that facilitate water loss. Thus, pomegranates should be handled with as much care as apples during harvesting and postharvest handling."
}

chickpea =  {
    "NAME":"Chickpea", 
    "TYPE":"Pulses",
     "DESCRIPTION": "Chick pea occupies Gram commonly known as 'chick pea' or Bengal gram is the most important pulse crop in India. about 38 per cent of area under pulses and contributes about 50 per cent of the total pulse production of India. It is used for human consumption as well as for feeding to animals. It is eaten both whole fried or boiled and salted or more generally in the form of split pulse which is cooked and eaten. Both husks and bits of the 'dal' are valuable cattle feed. Fresh green leaves are used as vegetable (sag). Straw of chick pea is an excellent fodder for cattle. The grains are also used as vegetable (chhole). Chick pea flour (besan) is used in the preparation of various types of sweets. Chick pea is considered to have medicinal effects and it is used for blood purification. Chick pea contains 21.1 per cent protein, 61.5 per cent carbohydrates, 4.5 per cent fat. It is rich in calcium, iron and niacin.",
     "DISEASES": "The important diseases of chick pea are wilt, sclerotinia blight, grey mold, rust and Ascochyta blight.",
     "COMPANION":"",
     "PESTS":" ",
     "FERTILIZER":"Chick pea being a leguminous crop fulfills the major part of its nitrogen requirement (about 75%) through the process of symbolic nitrogen fixation which works effectively from three to four weeks after sowing. However, soils with low organic matter and poor nitrogen supply may require 20-25 kg per hectare of nitrogen as starter does which can meet plant requirement before the formation of nodules. Besides nitrogen, pulses respond very favourably to phosphorous application if the soils are deficient in phosphorous supply. If both nitrogen and phosphorous are required to be supplied then diammonium phosphate (18-46-0) at the rate of 100 to 150 kg per hectare should be applied uniformly before the last discingploughing. Responses to potassium application have been inconsistent. It is better if all the fertilizers are drilled in furrows at a depth of 7-10 centimeters.",
     "TIPS": "No Tips",
     "SPACING":"",
     "WATERING":"Chick pea is mostly sown as a rainfed crop. However, where irrigation facilities are available, give a pre-sowing irrigation. It will ensure proper germination and smooth crop growth. If winter rains fail, give one irrigation at pre-flowering stage and one at pod development stage. In no case first irrigation should be given at flowering time of gram crop. A light irrigation should be given because heavy irrigation is always harmful to gram crop. Excess of irrigation enhances vegetative growth and depresses chick pea yield.",
     "STORAGE": ""
}

maize = {
    "NAME":"Maize", 
    "TYPE":"Cereal",
     "DESCRIPTION": "Maize is one of the important foods, green forage & industrial crops of the world. It is called QUEEN OF THE CEREALS. Maize has highest yield/ha among the cereal crops. ",
     "DISEASES": "Main diseases in maize farming are downy mildew and leaf spot. Downy mildew: To control this, remove the affected plants. Spray Metalaxyl 72 WP @ 1 kg per hectare, or Mancozeb 1 kg per hectare, 20 days after sowing. Leaf spot: To control this, spray Captain or Mancozeb kg per hectare when the disease intensity is high.",
     "COMPANION":"",
     "PESTS":" ",
     "FERTILIZER":"Other than Farm Yard Manure applied at the time of land preparation, should apply inorganic fertilizers like 470 kg of superphosphate, 200 kg of urea, and 180 kg of potash per ha as a basal dose. 20 days after sowing, should apply 50 to 60 kg of urea and at 40 days after sowing 120 kg of urea and 50 kg of potash as a topdressing.",
     "TIPS": "",
     "SPACING":"60×25cm or 75×20cm But crop geometry of 45×20cm is found to be optimum for most of the areas.",
     "WATERING":"As soon as sowing is done, immediate irrigation is required in the field. Subsequently, give life irrigation on the third or fourth day and based on the soil type and season. (It may not be required in rainy season). Usually for maize crop, up to 25 to 30 days, less number of irrigation is recommended, afterward, it is required to irrigate once in a week. During the early stage of this crop, water stagnation should be avoided and should have good drainage.",
     "STORAGE": ""
}

coffee =  {
    "NAME":"COFFEE", 
    "TYPE":"fruit",
     "DESCRIPTION": "In India, coffee is traditionally grown in the Western Ghats spread over Karnataka, Kerala and Tamil Nadu. Coffee cultivation is also being expanding rapidly in the nontraditional areas of Andhra Pradesh and Odisha as well as in the North East states. Coffee is predominantly an export oriented commodity and 65% to 70% of coffee produced in the country is exported while the rest is consumed within the country. Indian coffee has created a niche for itself in the international market and the Indian Coffees are earning high premium, particularly Indian Robusta which is highly preferred for its good blending quality. Arabica Coffee from India is also well received in the international market.The two main varieties of coffee viz., Arabica and Robusta are grown in India.",
     "DISEASES": " coffee leaf rust (Himeleia vastatrix), black rot (Koleroga noxia) and root diseases are the major ones that cause crop losses.",
     "COMPANION":"Cultivating fruits such as avocado, longan, rambutan, egg fruit and mangosteen as intercrop for coffee would help farmers get additional income.",
     "PESTS":" white stem borer (Xylotrechus quadripes), coffee berry borer (Hypothenemus hampei), shot hole borer (Xylosandrus compactus), nematodes and sucking pests like mealybugs and green scales are of economic importance.",
     "FERTILIZER":"Higher yielding coffee plots may require 25% more fertiliser. Use lime or preferably, dolomite (Ca + Mg) at 500 g per plant every two years and apply before the end of the rainy season. Use the last rains to wash the lime into the soil or water in well by hand or irrigation.",
     "TIPS": "Plant the coffee tree in a warm situation, either in full sun or part sun/shade. The leaves will be a deeper green colour when grown in part shade. As with all fruit trees, improve the soil with organic matter before planting and it's also a good idea to do a pH test before planting.",
     "SPACING":"coffee arabica:2 x 2 m,coffee robusta:3 x 3 m",
     "WATERING":"The frequency of irrigation in coffee growing depends on the soil-types-suitable-crops-india, moisture level in the soil, plant age and climate. There are many irrigation methods are available like drip irrigation, components-cost sprinkler irrigation, microjet, and basin irrigation can be adopted in coffee Growing. However, drip irrigation is the best method for best utilization of water and fertilizers. This can also control weed growth at plant basins. Under irrigated conditions, each coffee plant requires 50 to 55 mm water and this should be applied before transplanting. Subsequent irrigations of 25 mm should be provided at 8 to 10 days interval. &nbsp;Make sure to keep the soil moist and avoid too much wetness. Overwatering can result in plantrot and fungal diseases in coffee growing. The thumb rule is to provide 2 irrigations in a week in dry climatic conditions (like in summer) and 1 irrigation per week in the cool winter season.",
     "STORAGE": "As air temperature rises, it can retain more water molecules. In other words, warmer air means more moisture in the air and cooler air means less moisture in the air. This leads to the logical conclusion that cool air is better for green bean coffee storage. Many experts suggest storing beans at room temperature."
}

Lentil =  {
    "NAME":"Lentil", 
    "TYPE":"Pulses",
     "DESCRIPTION": "Lentil is a valuable human food, mostly consumed as dry seeds (whole decorticated, seed decorticated and split). In India, its mostly consumed as ‘Dal’ by removal of outer skin and separation of cotyledons. It is easy to cook and easily digestible with high biological value. Dry leaves, stems, empty and broken pods are used as valuable cattle feed.Lentil is also called as Masur and Malka (bold seeded). The Lentil growing states in India are Madhya Pradesh, Uttar Pradesh, Bihar, Chattisgarh, Haryana, Punjab, Maharashtra, Rajasthan, etc",
     "DISEASES": "The major diseases of lentil are rust in northern plain and wilt in Central zone. Use of resistant varieties is helpful in controlling the disease - small seeded Rust resistant : PL-406, PL-639, PL-4, and L-4147 ;  bold seeded Rust resistant : L- 4076, DPL-15, IPL-406, DPL-62 etc.",
     "COMPANION":"Most common inter cropping systems are: Lentil + Sugarcane (Autumn) with two rows of lentil at 30 cm row spacing in between two rows of sugarcane Lentil + Linseed (2:2) Lentil + Mustard (2:6 )",
     "PESTS":"Pest is not a major problem in lentil. In some years aphid population rises due to rise in temperature during January of February, and causes heavy damage. Spray of Monocrotophos (0.04%) is effective for aphid control. ",
     "FERTILIZER":"Generally Nitrogen 20 kg. Phosphorus 40 kg. and Sulphur 20 kg. per hectare in medium to low fertile soils as basal dressing. In lentil grown in calcareous alluvial soils, apply 1.6 kg of Boron per ha as basal to each crop. In soils, low in Zn, soil application of 20 kg Zinc Sulphate is recommended under rainfed and late sown condition; foliar spray of 2% urea improves yield.",
     "TIPS": "Deep summer ploughing once in 3 years. Seed treatment should be done before sowing. Application of fertilizer should be based on soil test value. Wilt resistant/ tolerant – RV L - 31, IPL81 (Noori), IPL - 316, Sekhar masoor - 2, Sekhar masoor - 2. 5. Rust resistant/ tolerant – IPL - 406, WBL - 77, Pant L - 6, Pant L - 7, Sekhar masoor - 2, Sekhar masoor - 2, IPL - 316.",
     "SPACING":"Sowing should be done in rows 30 cm. apart and it should be sown at a lower depth (3 - 4 cm). This could be done either by using a Ferti-seed-drill or by seeding behind desi plough.",
     "WATERING":"First irrigation should be given at 40 - 45 days of planting and second at pod filling stage. Most critical stage for moisture stress is pod formation followed by flower initiation. In absence of winter rains and where contribution of soil moisture is negligible viz . in Central India, two light irrigations may be applied for significant yield improvement. More irrigation may affect the crop performance adversely.",
     "STORAGE": "The crop should be allowed to dry for 4-7 days on threshing floor and threshed by manually or bullock/power drawn thresher. The clean seed should be sun dried for 3-4 days to bring their moisture content at 9-10%. The seed should be safely stored in appropriate bins and fumigated to protect them from bruchids. Yield - A well mange crop yields about 15 - 20 quintals of grain per hectare."
}
